config/routes.rb
get 'issues/:id/statuses_spent_time', controller: :rm_issue_tabs, action: :statuses_spent_time, as: :statuses_spent_time

app/models/rm_issue_time_statistic.rb
class RmIssueTimeStatistic < ActiveRecord::Base
  include Redmine::SafeAttributes
  belongs_to :user, foreign_key: :user_id
  belongs_to :issue
  belongs_to :status, class_name: 'IssueStatus', foreign_key: :status_id

  safe_attributes 'id', 'created_at', 'updated_at', {unsafe: true}
end

app/controllers/rm_issue_tabs_controller.rb
class RmIssueTabsController < ApplicationController
  before_action :require_login

  include RmIssueTimeStatisticsHelper
  helper :rm_issue_time_statistics

  def statuses_spent_time
    @issue = Issue.where(id: params[:id]).first
  end
end

app/helpers/rm_issue_time_statistics_helper.rb
module RmIssueTimeStatisticsHelper
  def hourize(seconds, options={})
    return 'x' if (seconds.nil?)
    result = []
    if (seconds == 0)
      result << wrap_value(0, I18n.t('rm_time_statistics.label_hours'))
    else
      seconds = seconds.to_i
      days = 0
      if (options[:without_days].nil? || !options[:without_days])
        days = (seconds / 86400).to_i
        seconds = seconds - (days * 86400)
      end
      hours = (seconds / 3600).to_i
      seconds = seconds - (hours * 3600)
      minutes = (seconds / 60).to_i
      seconds = seconds - (minutes * 60)

      result << wrap_value(days, I18n.t('rm_time_statistics.label_days')) if (days > 0)
      result << wrap_value(hours, I18n.t('rm_time_statistics.label_hours')) if (hours > 0)
      result << wrap_value(minutes, I18n.t('rm_time_statistics.label_minutes')) if (minutes > 0)
      result << wrap_value(seconds, I18n.t('rm_time_statistics.label_seconds')) if (seconds > 0 && days <= 0 && hours <= 0)
    end

    result.join(' ').html_safe
  end

  def wrap_value(value, unit)
    "<span class='cp_value_normal'>#{value}</span><span class='cp_unit_def'>#{unit}</span>".html_safe
  end
end

app/views/hooks/rm_issue_tabs/_view_issues_show_details_bottom.html.erb
<% statuses_spent_time =  {
    name: 'statuses_spent_time', label: :label_rm_statuses_time_spent,
    onclick: "getRemoteTab('statuses_spent_time', '#{statuses_spent_time_path(@issue)}', '#{issue_path(@issue, :tab => 'statuses_spent_time')}')",
    partial: 'rm_issue_tabs/statuses_spent_time',
    locals: {:issue => @issue},
    remote: true,
} %>
<script type="text/javascript" charset="utf-8">
  $(document).ready(function () {
    $('#history').html('<%= j render_tabs(issue_history_tabs + [statuses_spent_time], issue_history_default_tab).html_safe %>');
  })
</script>

app/views/hooks/rm_issue_tabs/_view_layouts_base_html_head.html.erb
<%= stylesheet_link_tag 'rm_issue_tabs', plugin: :rm_issue_tabs %>

app/views/rm_issue_tabs/_statuses_spent_time.html.erb
<% if @issue && @issue.rm_time_statistics_aggregate.present? %>
  <table class="list issue-report rm_statuses_spent_time">
    <thead>
      <tr>
        <th><%= l(:field_status) %></th>
        <th><%= l(:label_total_spent_time) %></th>
      </tr>
    </thead>
    <tbody>
      <% @issue.rm_time_statistics_aggregate.each do |status| %>
        <% total_time = status.avg_time * status.avg_count %>
        <% if status.status_id.to_i == @issue.status_id  %>
          <% total_time = total_time + (Time.now.utc - @issue.rm_time_statistic_last.created_on.to_datetime.utc) %>
        <% end %>
        <tr>
          <td><%= status.status_name %></td>
          <td><%= hourize(total_time) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="nodata"><%= l(:label_no_data) %></div>
<% end %>